FROM centos:latest
RUN yum -y install wget
WORKDIR /root
RUN wget https://downloads.mariadb.com/MariaDB/mariadb-10.2.12/yum/rhel/mariadb-10.2.12-rhel-7-x86_64-rpms.tar
RUN tar xvf mariadb-10.2.12-rhel-7-x86_64-rpms.tar
RUN mariadb-10.2.12-rhel-7-x86_64-rpms/setup_repository
RUN yum -y install MariaDB-server
COPY maxuser.sh /root/
RUN /etc/init.d/mysql start
#RUN mysql < maxuser.sh
